server:
  port: 8180

spring:
  datasource:
    url: jdbc:postgresql://devdb.cby02zmi8jpc.us-east-1.rds.amazonaws.com:5432/devdb
    username: rfaduser
    password: rfaduser
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: ${db.schema}
  liquibase:
    default-schema: ${db.schema}
    
  profiles:
    active: local
    
db:
  schema: rfaduser